gui-strings:
  'false': '&cfalse'
  'true': '&atrue'
  value: '&bValue: '
  separator: '&7|'
gui-separator:
  material: THIN_GLASS
  data: 0
gui-flags:
  door:
    slot: 0
    material: WOOD_DOOR
    name: '&e=> Allow Door Open'
    description: '&6Description: &aAllow no members to open'
    description1: '&aand close doors in this region.'
    description2: ''
  smart-door:
    slot: 1
    material: IRON_DOOR
    name: '&e=> Open Double and Iron Doors'
    description: '&6Description: &aAllow members to open'
    description1: '&asingle and double normal and iron doors'
    description2: '&aand iron trap doors.'
  pvp:
    slot: 20
    material: STONE_SWORD
    name: '&e=> Allow PvP'
    description: '&6Description: &aAllow PvP for all players'
    description1: '&ain this region, including members and'
    description2: '&ano members.'
  allow-home:
    slot: 2
    material: BED
    name: '&e=> Allow Set Home'
    description: '&6Description: &aAllow no members to use the'
    description1: '&acommand /sethome or /home to set or come to'
    description2: '&athis region.'
  chest:
    slot: 3
    material: TRAPPED_CHEST
    name: '&e=> Allow Chest Access'
    description: '&6Description: &aAllow no members to access'
    description1: '&athis chest for take and put itens.'
    description2: ''
  lever:
    slot: 5
    material: LEVER
    name: '&e=> Use Lever'
    description: '&6Description: &aAllow no members to use'
    description1: '&alevers in this region.'
    description2: ''
  button:
    slot: 6
    material: WOOD_BUTTON
    name: '&e=> Use Buttons'
    description: '&6Description: &aAllow no members to use'
    description1: '&abuttons in this region.'
    description2: ''
  passives:
    slot: 33
    material: SADDLE
    name: '&e=> Hurt Passives'
    description: '&6Description: &aAllow no members to hurt,'
    description1: '&akill or interact with passives mobs in'
    description2: '&athis region.'
  allow-magiccarpet:
    slot: 7
    material: GLASS
    name: '&e=> Allow Magic Carpet'
    description: '&6Description: &aAllow players walk with'
    description1: '&aMagic Carpet in your region'
    description2: ''
  minecart:
    slot: 25
    material: MINECART
    name: '&e=> Allow Place Minecarts'
    description: '&6Description: &aAllow no members to place,'
    description1: '&aenter and break Minecarts in this region.'
    description2: ''
  fire:
    slot: 28
    material: BLAZE_POWDER
    name: '&e=> Fire Spread and Damage Blocks'
    description: '&6Description: &aAllow damage blocks by fire'
    description1: '&aand explosion, and fire spread.'
    description2: ''
  flow:
    slot: 29
    material: WATER_BUCKET
    name: '&e=> Water and Lava Flow'
    description: '&6Description: &aEnable water and lava flow'
    description1: '&ain this region.'
    description2: ''
  spawn-animals:
    slot: 34
    material: EGG
    name: '&e=> Spawn Animals'
    description: '&6Description: &aAllow natural spawn of'
    description1: '&apassives mobs in this region.'
    description2: ''
  spawn-monsters:
    slot: 35
    material: PUMPKIN
    name: '&e=> Spawn Monsters'
    description: '&6Description: &aAllow natural spawn of'
    description1: '&amonsters in this region.'
    description2: ''
  use-potions:
    slot: 15
    material: GLASS_BOTTLE
    name: '&e=> Allow Use Potions'
    description: '&6Description: &aAllow use or throw'
    description1: '&aany type of potions for non members'
    description2: '&aof region.'
  allow-effects:
    slot: 16
    material: BLAZE_ROD
    name: '&e=> Allow Effects'
    description: '&6Description: &aAllow or cancel all'
    description1: '&atype of effects for non members'
    description2: '&aof this region.'
  mob-loot:
    slot: 32
    material: GRASS
    name: '&e=> Allow Mob Grief'
    description: '&6Description: &aAllow mobs to damage,'
    description1: '&aexplode or grief blocks on this'
    description2: '&aregion.'
  flow-damage:
    slot: 30
    material: LAVA_BUCKET
    name: '&e=> Allow Flow Damage'
    description: '&6Description: &aAllow liquids to'
    description1: '&aremove blocks on flow.'
    description2: ''
  iceform-world:
    slot: 31
    material: ICE
    name: '&e=> Allow Ice Form by World'
    description: '&6Description: &aAllow ice form'
    description1: '&aby entitys like SnowMan and by'
    description2: '&aweather like snow.'
  iceform-player:
    slot: 4
    material: PACKED_ICE
    name: '&e=> Allow Ice Form by Players'
    description: '&6Description: &aAllow ice form'
    description1: '&aby players using frost walk'
    description2: '&aenchant.'
  allow-fly:
    slot: 8
    material: FEATHER
    name: '&e=> Allow Fly'
    description: '&6Description: &aAllow players with'
    description1: '&afly enabled to fly on this region.'
    description2: ''
  teleport:
    slot: 19
    material: ENDER_PEARL
    name: '&e=> Allow Teleport'
    description: '&6Description: &aAllow players to'
    description1: '&ateleport on this region using itens'
    description2: '&alike ender pearls and chorus fruits.'
  clan:
    slot: 14
    material: BOW
    name: '&e=> Set Clan Region'
    description: '&bDescription: &aSet this region as'
    description1: '&ayour clan home, adding all clan members'
    description2: '&aat same time with on click.'
  ender-chest:
    slot: 22
    material: ENDER_CHEST
    name: '&e=> Allow EnderChest Access'
    description: '&bDescription: &aAllow players to'
    description1: '&ause ender chests on this region.'
    description2: ''
  can-grow:
    slot: 27
    material: WHEAT
    name: '&e=> Allow Farms to Grow'
    description: '&bDescription: &aChoose if farms'
    description1: '&ain this region will grow or not.'
    description2: ''
  allow-spawner:
    slot: 10
    material: MOB_SPAWNER
    name: '&e=> Allow Place or Break Spawners'
    description: '&bDescription: &aAllow non members'
    description1: '&aof this region to break or'
    description2: '&aplace mob spawners.'
  leaves-decay:
    slot: 11
    material: LEAVES
    name: '&e=> Allow Leaves Decay or Not'
    description: '&bDescription: &aAllow leaves decay'
    description1: '&anaturally or not.'
    description2: ''
  build:
    slot: 13
    material: COBBLESTONE
    name: '&e=> Allow Build'
    description: '&bDescription: &aAllow non members to'
    description1: '&abuild on region. This mean break and'
    description2: '&aplace blocks.'
