gui-strings:
  'false': '&cfalse'
  'true': '&atrue'
  value: '&bValue: '
  separator: '&7|'
gui-separator:
  material: THIN_GLASS
  data: 0
gui-flags:
  door:
    slot: 0
    material: WOOD_DOOR
    name: '&e=> Allow Door Open'
    description: '&6Description: &aAllow no members to open'
    description1: '&aand close doors in this region.'
    description2: ''
  smart-door:
    slot: 1
    material: IRON_DOOR
    name: '&e=> Open Double and Iron Doors'
    description: '&6Description: &aAllow members to open'
    description1: '&asingle and double normal and iron doors'
    description2: '&aand iron trap doors.'
  pvp:
    slot: 13
    material: STONE_SWORD
    name: '&e=> Allow PvP'
    description: '&6Description: &aAllow PvP for all players'
    description1: '&ain this region, including members and'
    description2: '&ano members.'
  allow-home:
    slot: 2
    material: BED
    name: '&e=> Allow Set Home'
    description: '&6Description: &aAllow no members to use the'
    description1: '&acommand /sethome or /home to set or come to'
    description2: '&athis region.'
  chest:
    slot: 3
    material: TRAPPED_CHEST
    name: '&e=> Allow Chest Access'
    description: '&6Description: &aAllow no members to access'
    description1: '&athis chest for take and put itens.'
    description2: ''
  lever:
    slot: 5
    material: LEVER
    name: '&e=> Use Lever'
    description: '&6Description: &aAllow no members to use'
    description1: '&alevers in this region.'
    description2: ''
  button:
    slot: 6
    material: WOOD_BUTTON
    name: '&e=> Use Buttons'
    description: '&6Description: &aAllow no members to use'
    description1: '&abuttons in this region.'
    description2: ''
  passives:
    slot: 24
    material: SADDLE
    name: '&e=> Hurt Passives'
    description: '&6Description: &aAllow no members to hurt,'
    description1: '&akill or interact with passives mobs in'
    description2: '&athis region.'
  allow-magiccarpet:
    slot: 8
    material: GLASS
    name: '&e=> Allow Magic Carpet'
    description: '&6Description: &aAllow players walk with'
    description1: '&aMagic Carpet in your region'
    description2: ''
  minecart:
    slot: 18
    material: MINECART
    name: '&e=> Allow Place Minecarts'
    description: '&6Description: &aAllow no members to place,'
    description1: '&aenter and break Minecarts in this region.'
    description2: ''
  fire:
    slot: 19
    material: BLAZE_POWDER
    name: '&e=> Fire Spread and Damage Blocks'
    description: '&6Description: &aAllow damage blocks by fire'
    description1: '&aand explosion, and fire spread.'
    description2: ''
  flow:
    slot: 20
    material: WATER_BUCKET
    name: '&e=> Water and Lava Flow'
    description: '&6Description: &aEnable water and lava flow'
    description1: '&ain this region.'
    description2: ''
  spawn-animals:
    slot: 25
    material: EGG
    name: '&e=> Spawn Animals'
    description: '&6Description: &aAllow natural spawn of'
    description1: '&apassives mobs in this region.'
    description2: ''
  spawn-monsters:
    slot: 26
    material: PUMPKIN
    name: '&e=> Spawn Monsters'
    description: '&6Description: &aAllow natural spawn of'
    description1: '&amonsters in this region.'
    description2: ''
  allow-potions:
    slot: 7
    material: GLASS_BOTTLE
    name: '&e=> Allow Potions'
    description: '&6Description: &aAllow use or throw'
    description1: '&aany type of potions for no members'
    description2: '&aof region.'
  mob-loot:
    slot: 23
    material: GRASS
    name: '&e=> Allow Mob Grief'
    description: '&6Description: &aAllow mobs to damage,'
    description1: '&aexplode or grief blocks on this'
    description2: '&aregion.'
  flow-damage:
    slot: 21
    material: LAVA_BUCKET
    name: '&e=> Allow Flow Damage'
    description: '&6Description: &aAllow liquids to'
    description1: '&aremove blocks on flow.'
    description2: ''