gui-strings:
  'false': '&cfalse'
  'true': '&atrue'
  value: '&bValue: '
  separator: '&7|'
gui-separator:
  material: THIN_GLASS
  data: 0
gui-flags:
  door:
    slot: 0
    material: WOOD_DOOR
    name: '&e=> 允许开门'
    description: '&6描述: &a允许在此地区非成员玩家开门以及关门'
    description1: ''
    description2: ''
  smart-door:
    slot: 1
    material: IRON_DOOR
    name: '&e=> 打开大门和铁门'
    description: '&6描述: &a允许成员打开单双普通门和铁门和陷阱门'
    description1: ''
    description2: ''
  pvp:
    slot: 20
    material: STONE_SWORD
    name: '&e=> 允许 PvP（允许杀人）'
    description: '&6描述: &a允许在此区域PvP包括成员与非成员玩家。'
    description1: ''
    description2: ''
  allow-home:
    slot: 2
    material: BED
    name: '&e=> 允许设定家'
    description: '&6描述: z&a允许非成员玩家在此区域输入或使用 /sethome 或 /home 命令'
    description1: ''
    description2: ''
  chest:
    slot: 3
    material: TRAPPED_CHEST
    name: '&e=> 允许打开箱子'
    description: '&6描述: &a允许非成员玩家打开这个箱子进行操作'
    description1: ''
    description2: ''
  lever:
    slot: 5
    material: LEVER
    name: '&e=> 使用杠杆'
    description: '&6描述: &a允许非成员玩家在此区域使用杠杆'
    description1: ''
    description2: ''
  button:
    slot: 6
    material: WOOD_BUTTON
    name: '&e=> 使用按钮'
    description: '&6描述: &a允许非成员玩家在此区域使用按钮'
    description1: ''
    description2: ''
  passives:
    slot: 33
    material: SADDLE
    name: '&e=> 攻击非主动攻击动物'
    description: '&6描述: &a允许非成员玩家在此区域对不主动攻击的动物作出任何动作。'
    description1: ''
    description2: ''
  allow-magiccarpet:
    slot: 7
    material: GLASS
    name: '&e=> 允许魔法毯'
    description: '&6描述: &a允许玩家使用魔法毯走进你的区域'
    description1: ''
    description2: ''
  minecart:
    slot: 25
    material: MINECART
    name: '&e=> 允许放置矿车'
    description: '&6描述: &a允许非成员玩家在此区域进入矿车以及打坏矿车'
    description1: ''
    description2: ''
  fire:
    slot: 28
    material: BLAZE_POWDER
    name: '&e=> 火势蔓延以及损坏方块'
    description: '&6描述: &a允许以火或爆炸或火势蔓延来损坏方块'
    description1: ''
    description2: ''
  flow:
    slot: 29
    material: WATER_BUCKET
    name: '&e=> 允许各种液体流动'
    description: '&6描述: &a允许在此区域出现水流或岩浆流'
    description1: ''
    description2: ''
  spawn-animals:
    slot: 34
    material: EGG
    name: '&e=> 刷新动物'
    description: '&6描述: &a允许在此区域自然生成非主动攻击动物'
    description1: ''
    description2: ''
  spawn-monsters:
    slot: 35
    material: PUMPKIN
    name: '&e=> 刷新怪物'
    description: '&6描述: &a允许在此区域自然生成怪物'
    description1: ''
    description2: ''
  use-potions:
    slot: 15
    material: GLASS_BOTTLE
    name: '&e=> 允许使用药水'
    description: '&6描述: &a允许非成员玩家在此区域使用或扔出任何类型的药水'
    description1: ''
    description2: ''
  allow-effects:
    slot: 16
    material: BLAZE_ROD
    name: '&e=> 允许效果'
    description: '&6描述: &a允许或取消非成员玩家在此区域所拥有的任何效果'
    description1: ''
    description2: ''
  mob-loot:
    slot: 32
    material: GRASS
    name: '&e=> 允许动物或怪物破坏方块'
    description: '&6描述: &a允许动物或怪物在此区域对方块进行破坏'
    description1: ''
    description2: ''
  flow-damage:
    slot: 30
    material: LAVA_BUCKET
    name: '&e=> 允许各种液体流动造成的破坏'
    description: '&6描述: &a允许液体流动来移除方块'
    description1: ''
    description2: ''
  iceform-world:
    slot: 31
    material: ICE
    name: '&e=> 允许让世界物体产生冰盖'
    description: '&6描述: &a允许让世界物体产生冰盖。例如雪人和下雪的时候。'
    description1: ''
    description2: ''
  iceform-player:
    slot: 4
    material: PACKED_ICE
    name: '&e=> 允许让玩家造冰盖'
    description: '&6描述: &a允许玩家使用冰霜行者附魔产生冰盖。'
    description1: ''
    description2: ''
  allow-fly:
    slot: 8
    material: FEATHER
    name: '&e=> 允许飞行'
    description: '&6描述: &a允许玩家在此区域飞行'
    description1: ''
    description2: ''
  teleport:
    slot: 19
    material: ENDER_PEARL
    name: '&e=> 允许传送'
    description: '&6描述: &a允许玩家在此区域使用例如紫颂果或末影珍珠来进行传送。'
    description1: ''
    description2: ''
  clan:
    slot: 14
    material: BOW
    name: '&e=> 设定公会区域'
    description: '&b描述: &a设定这个区域为公会基地，在点击的时候同一时间，所有公会成员添加进这个区域'
    description1: ''
    description2: ''
  ender-chest:
    slot: 22
    material: ENDER_CHEST
    name: '&e=> 允许打开末影箱'
    description: '&b描述: &a允许玩家在此区域使用末影箱'
    description1: ''
    description2: ''
  can-grow:
    slot: 27
    material: WHEAT
    name: '&e=> 允许让农作物成长'
    description: '&b描述: &a选择是否在此区域让农作物成长'
    description1: '&a'
    description2: ''
  allow-spawner:
    slot: 10
    material: MOB_SPAWNER
    name: '&e=> 允许放置或者破坏刷怪箱'
    description: '&b描述: &a允许非成员在此区域放置或破坏刷怪箱'
    description1: ''
    description2: ''
  leaves-decay:
    slot: 11
    material: LEAVES
    name: '&e=> 是否允许叶子凋零'
    description: '&b描述: &a是否允许叶子自然凋零'
    description1: ''
    description2: ''
  build:
    slot: 13
    material: COBBLESTONE
    name: '&e=> 允许建筑'
    description: '&b描述: &a允许非成员玩家在此区域建造。 这意味着可以破坏或者放置方块。'
    description1: ''
    description2: ''