# This workflow runs when a new tag starting with 'v' is pushed.
# It builds the plugin with the tag version, creates a GitHub Release, and uploads the final JAR.
#  For buils on github, push tags:
#  - git tag v1.0.0
#  - git push origin --tags
name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22 and Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set Release Version
        run: |
          TAG_VERSION=$(echo ${GITHUB_REF#refs/tags/v})
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
          # Use o versions-maven-plugin para definir a vers√£o em todos os POMs
          mvn -B versions:set -DnewVersion=${TAG_VERSION} -DprocessAllModules=true -DgenerateBackupPoms=false

      - name: Build for Release
        run: |
          # Agora, apenas compile. A vers√£o j√° est√° correta nos POMs.
          mvn -B clean install -DBUILD_NUMBER=${{ github.run_number }} -Dmaven.javadoc.skip -Dmaven.source.skip -Dgpg.skip --file pom.xml
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Generate Release Notes
        id: generate_releasenotes
        run: |
          # Check if this is the first push (or tag on initial commit).
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "First push (or tag on initial commit). Listing all commits in this push."
            CHANGELOG=$(echo '${{ toJSON(github.event.commits) }}' | jq -r '.[].message' | sed 's/^/- /')
          else
            # Generate a changelog based on the commits in the push
            CHANGELOG=$(git log ${{ github.event.before }}..${{ github.event.after }} --pretty=format:"- %s")
          fi

          BODY="## What's New
          ${CHANGELOG}
          
          ---
          
          More about:
          [**SpigotMC**](https://www.spigotmc.org/resources/redprotect-anti-grief-server-protection-region-management-mod-mobs-flag-compat-1-7-1-21.15841/)
          [**RedProtect Wiki**](https://github.com/FabioZumbi12/RedProtect/wiki)"
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "${BODY}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: RedProtect v${{ env.TAG_VERSION }} - Build ${{ github.run_number }} - Official Release
          body: ${{ steps.generate_releasenotes.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RedProtect-Spigot/target/RedProtect-${{ env.TAG_VERSION }}-b${{ github.run_number }}-Spigot.jar
          asset_name: RedProtect-${{ env.TAG_VERSION }}-b${{ github.run_number }}-Spigot.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord Notification
        uses: avaste/action-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embeds: |
            [{
              "title": "üöÄ New Release: RedProtect ${{ github.ref_name }}",
              "description": "A new official version has been released!\n\n${{ steps.generate_releasenotes.outputs.changelog }}",
              "url": "${{ steps.create_release.outputs.html_url }}",
              "color": 3066993,
              "author": {
                "name": "${{ github.repository_owner }}",
                "url": "https://github.com/${{ github.repository_owner }}",
                "icon_url": "https://github.com/${{ github.repository_owner }}.png"
              },
              "footer": {
                "text": "Build #${{ github.run_number }}"
              }
            }]
